---
- hosts: all 
  become: True
  tasks:
    - name: Install packages
      dnf:
        name: 
          - httpd
          - wget
          - mysql
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
